name: Run Tests
on: push
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - working-directory: testing
        run: python -m unittest -v 
      